
import React, { useState } from 'react';
import { generateGameWorld, generateGameThumbnail } from '../services/geminiService';
import { GameExperience, BloxObject, UserProfile } from '../types';

interface StudioProps {
  onPlay: (game: GameExperience) => void;
  user: UserProfile;
}

const Studio: React.FC<StudioProps> = ({ onPlay, user }) => {
  const [prompt, setPrompt] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedGame, setGeneratedGame] = useState<GameExperience | null>(null);
  const [status, setStatus] = useState('');
  const [selectedObjectId, setSelectedObjectId] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (!prompt.trim()) return;
    
    setIsGenerating(true);
    setStatus('Asking Gemini to design the universe...');
    
    try {
      const gameData = await generateGameWorld(prompt);
      setStatus('Generating custom graphics...');
      const thumbnail = await generateGameThumbnail(prompt);
      
      const fullGame: GameExperience = {
        id: Math.random().toString(36).substr(2, 9),
        title: gameData.title || 'AI Experience',
        description: gameData.description || 'Generated by Blox AI Studio',
        creator: user.username,
        thumbnail: thumbnail,
        objects: gameData.objects || [],
        instructions: gameData.instructions || 'Explore the world!'
      };
      
      setGeneratedGame(fullGame);
    } catch (error) {
      console.error(error);
      alert('Failed to build world. The AI is taking a coffee break.');
    } finally {
      setIsGenerating(false);
      setStatus('');
    }
  };

  const updateObject = (id: string, updates: Partial<BloxObject>) => {
    if (!generatedGame) return;
    setGeneratedGame({
      ...generatedGame,
      objects: generatedGame.objects.map(obj => obj.id === id ? { ...obj, ...updates } : obj)
    });
  };

  const selectedObject = generatedGame?.objects.find(o => o.id === selectedObjectId);

  return (
    <div className="max-w-6xl mx-auto space-y-8 pb-20">
      <div className="bg-white rounded-3xl p-8 shadow-sm border border-gray-100 flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex items-center space-x-4">
          <div className="p-3 bg-blue-100 rounded-2xl text-2xl">🛠️</div>
          <div>
            <h2 className="text-3xl font-black">Blox AI Studio</h2>
            <p className="text-gray-500">Describe your dream world and Gemini will build it in seconds.</p>
          </div>
        </div>
        {user.buildersClub !== 'None' && (
           <div className="bg-orange-100 border border-orange-200 px-4 py-2 rounded-2xl flex items-center space-x-2">
             <span className="text-orange-600 font-black">PRO</span>
             <span className="text-xs font-bold text-orange-800">Builders Club Member</span>
           </div>
        )}
      </div>

      <div className="grid lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2 space-y-8">
          <div className="bg-white rounded-3xl p-8 shadow-sm border border-gray-100 space-y-4">
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="e.g., A parkour course in space with spinning neon rings and a treasure at the end..."
              className="w-full h-32 p-4 bg-gray-50 rounded-2xl border-2 border-transparent focus:border-blue-500 focus:ring-0 transition-all outline-none text-lg"
            />
            <button
              onClick={handleGenerate}
              disabled={isGenerating || !prompt.trim()}
              className="w-full bg-blue-600 text-white font-bold py-4 rounded-2xl shadow-lg hover:shadow-xl transition-all disabled:bg-gray-300 disabled:shadow-none flex items-center justify-center space-x-2"
            >
              {isGenerating ? (
                <>
                  <div className="animate-spin rounded-full h-5 w-5 border-2 border-white border-t-transparent" />
                  <span>{status}</span>
                </>
              ) : (
                <>
                  <span>🚀 Build Game</span>
                </>
              )}
            </button>
          </div>

          {generatedGame && (
            <div className="bg-white rounded-3xl overflow-hidden shadow-xl border border-gray-100 animate-in fade-in slide-in-from-bottom-4 duration-500">
              <div className="grid md:grid-cols-2">
                <img src={generatedGame.thumbnail} className="w-full h-64 object-cover md:h-full" alt="Preview" />
                <div className="p-8 space-y-4">
                  <div className="flex items-center justify-between">
                    <h3 className="text-2xl font-bold">{generatedGame.title}</h3>
                    <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-xs font-bold">READY</span>
                  </div>
                  <p className="text-gray-600 text-sm">{generatedGame.description}</p>
                  <div className="pt-4 flex space-x-3">
                    <button 
                      onClick={() => onPlay(generatedGame)}
                      className="flex-1 bg-green-500 text-white font-bold py-3 rounded-xl hover:bg-green-600 transition-colors"
                    >
                      Play Now
                    </button>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* World Edit Tool Panel */}
        <div className="space-y-6">
          <div className="bg-white rounded-3xl p-6 shadow-sm border border-gray-100">
            <h3 className="font-bold text-lg mb-4 flex items-center space-x-2">
              <span>🌎</span>
              <span>World Edit Tool</span>
            </h3>
            
            {generatedGame ? (
              <div className="space-y-4">
                <p className="text-xs font-bold text-gray-400 uppercase">Object List</p>
                <div className="max-h-60 overflow-y-auto space-y-2 pr-2">
                  {generatedGame.objects.map(obj => (
                    <button
                      key={obj.id}
                      onClick={() => setSelectedObjectId(obj.id)}
                      className={`w-full text-left p-3 rounded-xl text-sm font-bold flex items-center justify-between transition-all ${
                        selectedObjectId === obj.id ? 'bg-blue-600 text-white' : 'bg-gray-50 hover:bg-gray-100'
                      }`}
                    >
                      <span>{obj.type.toUpperCase()}: {obj.id.slice(0, 4)}</span>
                      <div className="w-3 h-3 rounded-full" style={{ backgroundColor: obj.color }} />
                    </button>
                  ))}
                </div>

                {selectedObject && (
                  <div className="pt-4 border-t border-gray-100 space-y-4 animate-in fade-in zoom-in-95 duration-200">
                    <div>
                      <label className="text-xs font-bold text-gray-400 uppercase mb-1 block">Color</label>
                      <div className="flex flex-wrap gap-2">
                        {['#FF0000', '#00FF00', '#0000FF', '#FFFF00', '#FF00FF', '#00FFFF', '#888888', '#FF4500'].map(c => (
                          <button 
                            key={c}
                            onClick={() => updateObject(selectedObject.id, { color: c })}
                            className={`w-6 h-6 rounded-full border-2 transition-transform ${selectedObject.color === c ? 'border-black scale-110' : 'border-transparent'}`}
                            style={{ backgroundColor: c }}
                          />
                        ))}
                      </div>
                    </div>
                    <div>
                      <label className="text-xs font-bold text-gray-400 uppercase mb-1 block">Size: {selectedObject.size}</label>
                      <input 
                        type="range" 
                        min="0.5" 
                        max="8" 
                        step="0.5"
                        value={selectedObject.size}
                        onChange={(e) => updateObject(selectedObject.id, { size: parseFloat(e.target.value) })}
                        className="w-full accent-blue-600"
                      />
                    </div>
                    <button 
                      onClick={() => {
                        setGeneratedGame({
                          ...generatedGame,
                          objects: generatedGame.objects.filter(o => o.id !== selectedObjectId)
                        });
                        setSelectedObjectId(null);
                      }}
                      className="w-full py-2 bg-red-50 text-red-600 font-bold rounded-xl text-xs hover:bg-red-100"
                    >
                      Delete Object
                    </button>
                  </div>
                )}
              </div>
            ) : (
              <div className="text-center py-10 text-gray-400 space-y-2">
                <p className="text-3xl">🏜️</p>
                <p className="text-xs font-bold">Build a game first to use editing tools.</p>
              </div>
            )}
          </div>
          
          <div className="p-6 bg-yellow-50 rounded-3xl border border-yellow-100">
            <h4 className="font-bold text-sm mb-2 flex items-center space-x-2">
              <span>💎</span>
              <span>Pro Tip</span>
            </h4>
            <p className="text-xs text-yellow-800 leading-relaxed font-medium">Builders Club members can add up to 500 objects manually using the advanced scripts panel! (Coming soon)</p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Studio;
